Fixed up backup script to work correctly

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,10 +1,10 @@
 #!/bin/bash
 
-INITIALIZE=0
+LATEST=latest
 DATE=`date "+%Y-%m-%d_%H:%M:%S"`
-EXCLUDE=(--exclude={/dev/{*,},/proc/{*,},/sys/{*,},/tmp/{*,},/run/{*,},/mnt/{*,},/media/{*,},/lost+found,/var/lib/pacman/sync/*,/home/*/.cache/*,/home/*/Mail/,/home/*/Music/,/home/*/Dropbox/})
-
-read DIALOG <<< "$(which whiptail dialog 2> /dev/null)"
+EXCLUDE_FILE=/etc/backups.exclude
+EXCLUDE=( --exclude={/dev/,/proc/,/sys/,/tmp/,/run/,/mnt/,/media/,/lost+found/,/var/lib/pacman/sync/,/home/*/.cache/} )
+RSYNC_ARGS=( --out-format="" --info=progress2 --delete --delete-excluded --no-inc-recursive --exclude-from="$EXCLUDE_FILE" "${EXCLUDE[@]}" )
 
 # awk program for parsing rsync progress
 AWK_PROG=$(cat <<EOF
@@ -22,9 +22,9 @@ EOF
 # Parse parameters
 while test $# -gt 0; do
 	case "$1" in
-	  --init)
-		  INITIALIZE=1
-		  shift
+	  -h|--help|-u|--usage)
+		  print_usage
+		  exit 0
 		  ;;
 	  *)
 		  break
@@ -33,60 +33,45 @@ while test $# -gt 0; do
 done
 
 print_usage() {
-	echo -e "Usage: $0 [--init] destination\n" >&2
-	echo -e "Backs up the entire filesystem (minus a few directories) to the destination directory.\n" >&2
-	echo -e "Options:"
-	echo -e "--init\t\tShould be specified on the first run to create the initial backup. All other backups will be snapshots based on the initial backup." >&2
+	echo -e "Usage: $0 destination\n" >&2
+	echo -e "Backs up the entire filesystem to the backup drive.\n" >&2
+	echo -e "See $EXCLUDE_FILE for the list of excluded files and directories.\n" >&2
 }
 
-if [ $# -lt 1 ]; then 
-	print_usage
-    exit 1
-elif [ $# -gt 1 ]; then
-    echo -e "Too many arguments.\n" >&2
-	print_usage
-    exit 1
-elif [ ! -d "$1" ]; then
-   echo "Invalid path: $1" >&2
+if [ ! -d "$1" ]; then
+   echo "Invalid backup path: $1" >&2
    exit 1
 elif [ ! -w "$1" ]; then
    echo "Directory not writable: $1" >&2
    exit 1
 fi
 
-case "$1" in
-  "/mnt") ;;
-  "/mnt/"*) ;;
-  "/media") ;;
-  "/media/"*) ;;
-  "/run/media") ;;
-  "/run/media/"*) ;;
-  *) echo "Destination not allowed." >&2 
-     exit 1 
-     ;;
-esac
+# TODO Check for an handle no space on device
 
-if [[ $INITIALIZE == 1 ]]; then
-	echo "Creating initial backup..."
-	mkdir -p $1/current
-	START=$(date +%s)
-
-	rsync -aAXvp --progress --info=progress2 /* $1/current "${EXCLUDE[@]}" \
-	 | awk "$AWK_PROG" \
-	 | sed --unbuffered 's/\%//g' \
-	 | $DIALOG --title "Backing up to $1" --gauge "Backing up the latest changes..." 10 70
-
-	FINISH=$(date +%s)
-	echo "Total time: $(( ($FINISH-$START) / 60 )) minutes, $(( ($FINISH-$START) % 60 )) seconds"
-fi
-
-echo "Backing up the latest changes..."
+BACKUP_DIR=$(realpath $1)
 START=$(date +%s)
 
-rsync -avp --progress --info=progress2 --link-dest=$1/current /* "$1/$DATE" "${EXCLUDE[@]}" \
- | awk "$AWK_PROG" \
- | sed --unbuffered 's/\%//g' \
- | $DIALOG --title "Backing up to $1" --gauge "Backing up the latest changes..." 10 70
+if [[ ! -L "$BACKUP_DIR/$LATEST" ]]; then
+	echo "Creating initial backup at $BACKUP_DIR/${DATE}..."
+
+	rsync -a "${RSYNC_ARGS[@]}" / "$BACKUP_DIR/$DATE" \
+	 | awk "$AWK_PROG" \
+	 | sed --unbuffered 's/\%//g' \
+	 | whiptail --gauge "Creating initial backup at $BACKUP_DIR/${DATE}..." 10 70 0
+else
+	echo "Backing up the latest changes to $BACKUP_DIR/${DATE}..."
+
+	rsync -a "${RSYNC_ARGS[@]}" --link-dest="$BACKUP_DIR/$LATEST" / "$BACKUP_DIR/$DATE" \
+	 | awk "$AWK_PROG" \
+	 | sed --unbuffered 's/\%//g' \
+	 | whiptail --gauge "Backing up the latest changes to $BACKUP_DIR/${DATE}..." 10 70 0
+
+fi
 
 FINISH=$(date +%s)
 echo "Total time: $(( ($FINISH-$START) / 60 )) minutes, $(( ($FINISH-$START) % 60 )) seconds"
+
+# Create a symlink to the latest backup
+cd $BACKUP_DIR
+rm -f $LATEST
+ln -s $DATE $LATEST
